# Generated by Django 5.2.5 on 2025-10-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='词条标题')),
                ('content', models.TextField(verbose_name='词条内容')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '词条',
                'verbose_name_plural': '词条',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(verbose_name='原内容')),
                ('new_content', models.TextField(verbose_name='新内容')),
                ('edit_summary', models.CharField(blank=True, max_length=200, verbose_name='编辑摘要')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='encyclopedia.entry', verbose_name='所属词条')),
            ],
            options={
                'verbose_name': '编辑历史',
                'verbose_name_plural': '编辑历史',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='encyclopedia/images/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='图片说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='encyclopedia.entry', verbose_name='所属词条')),
            ],
            options={
                'verbose_name': '词条图片',
                'verbose_name_plural': '词条图片',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.entry', verbose_name='词条')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['title'], name='encyclopedi_title_7fe275_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['category'], name='encyclopedi_categor_c0e583_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_at'], name='encyclopedi_created_25fe48_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author'], name='encyclopedi_author__2f548f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'entry')},
        ),
    ]
